version: '3.8'

services:
  backend:
    build: ./Backend
    container_name: todo-backend
    ports:
      - "5001:5001"
    volumes:
      - ./Backend:/app
    environment:
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=todotasks
    depends_on:
      - db
    networks:
      - todo-network

  db:
    image: mariadb:10.5
    container_name: todo-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: todotasks
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - todo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  todo-network:
    driver: bridge

volumes:
  mariadb_data: